# Generated by Django 3.2.4 on 2021-06-08 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='This is the title', max_length=150)),
                ('description', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('classcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.classcode')),
                ('subjectcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subjectcode')),
            ],
        ),
    ]
